services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - "../.env"
    environment:
      - POSTGRES_USER=torrelles
      - POSTGRES_PASSWORD=torrelles123
      - POSTGRES_DB=sudoko
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - "../.env"  
    environment:
      - PGADMIN_DEFAULT_EMAIL=torrelles@email.com
      - PGADMIN_DEFAULT_PASSWORD=torrelles123
    ports:
      - "5050:80"
    restart: always

volumes:
  mongodb_data:
  postgres_data: